---
version: "3.8"

services:
  homarr:
    hostname: ${COMPOSE_PROJECT_NAME}
    domainname: ${LOCAL_DOMAIN}
    image: ghcr.io/homarr-labs/homarr:${HOMARR_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    ports:
      - '7575:7575'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - homarr_appdata:/appdata
    environment:
      TZ: America/Los_Angeles
      SECRET_ENCRYPTION_KEY: ${SECRET_ENCRYPTION_KEY}
    dns_search: ${LOCAL_DOMAIN}
    networks:
      net1:
        ipv4_address: ${THIS_IP}

networks:
  net1:
    external: true
    name: ${LAN_NAME}

volumes:
  homarr_appdata:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},nolock,rw,soft,nfsvers=4.2"
      device: ":${NFS_PATH}/${COMPOSE_PROJECT_NAME}/appdata"
